version: 2.1
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:14.17.3
    steps:
      - checkout
      - run: echo "this is the build job"

  test:
    docker:
      - image: circleci/node:14.17.3
    steps:
      - checkout
      - run: echo "this is the build job"

  deploy:
    docker:
      - image: circleci/node:14.17.3
    steps:
      - checkout
      - run: echo "this is the deploy job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test