version: 2.1
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:14.17.3
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm ci

  test:
    docker:
      - image: circleci/node:14.17.3
    steps:
      - checkout
      - run:
          name: tests
          command: echo "npm test is run Successfully"

  deploy:
    docker:
      - image: circleci/node:14.17.3
    steps:
      - checkout
      - run:
          name: ssd-nodes
          command: ssh -o "StrictHostKeyChecking no" bdmade@208.87.134.239 "cd ~/artQuest; git pull; cd backend; npm run start"

# Orchestrate our job run sequence
workflows:
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: circle-ci-test