# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ circle-ci-test ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
      - run: yarn install
        working-directory: backend
      - name: Install dependencies
      - run: yarn build --clean
        working-directory: backend

