# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ circle-ci-test ]

jobs:
  checkout-code:
    runs-on: self-hosted
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v2

  build-backend:
    runs-on: self-hosted
    needs: checkout-code
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: INSTALL PROJECT DEPENDENCIES (YARN)
        run: yarn install

      - name: BUILD THE WEBPACK
        run: yarn build

  build-frontend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: INSTALL PROJECT DEPENDENCIES (YARN)
        run: yarn install

      - name: BUILD THE WEBPACK
        run: yarn build

