# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Art Quest CI

on:
  push:
    branches: [ circle-ci-test ]

jobs:
  checkout-code:
    runs-on: self-hosted
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v2

  build-backend:
    runs-on: self-hosted
    needs: checkout-code
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: CREATE PRODUCTION .ENV FILE
        run: aq_env_backend

      - name: INSTALL PROJECT DEPENDENCIES (YARN)
        run: yarn install

      - name: Enable Stapi EE
        run: strapi_ee

      - name: BUILD THE WEBPACK
        run: yarn build --clean

  build-frontend:
    runs-on: self-hosted
    needs: build-backend
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: CREATE PRODUCTION .ENV FILE
        run: aq_env_frontend

      - name: INSTALL PROJECT DEPENDENCIES (YARN)
        run: yarn install

      - name: BUILD THE WEBPACK
        run: yarn build --clean

  reload-process-manager:
    runs-on: self-hosted
    needs: [build-backend, build-frontend]
    steps:
      - name: Delete the Node Process Manager
        run: pm2 delete art_quest_backend art_quest_frontend
      - name: start the Node Process Manager
        run: pm2 start ecosystem.config.js -i 0