# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ circle-ci-test ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - run: yarn
      - run: yarn build
      - run: pm2 reload ecosystem.config.js -i 0
