# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ circle-ci-test ]

jobs:
  checkout-code:
    runs-on: self-hosted
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v2

  build-backend:
    runs-on: self-hosted
    needs: checkout-code
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: INSTALL PROJECT DEPENDENCIES (YARN)
        run: yarn install

      - name: CREATE .ENV FILE
        run: mv .env.production .env
        run: echo "DATABASE_HOST=$DATABASE_HOST" >> .env

      - name: Enable Stapi EE
        run: strapi_ee

      - name: BUILD THE WEBPACK
        run: yarn build --clean

  build-frontend:
    runs-on: self-hosted
    needs: build-backend
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: INSTALL PROJECT DEPENDENCIES (YARN)
        run: yarn install

      - name: BUILD THE WEBPACK
        run: yarn build --clean

  reload-process-manager:
    runs-on: self-hosted
    needs: [build-backend, build-frontend]
    steps:
      - name: Reload the Node Process Manager
        run: pm2 start ecosystem.config.js -i max

